platform :ios, '7.0'

target 'DDCryptor' do
	pod 'OpenSSL-Universal', '~> 1.0'
    pod 'GTMBase64', '~> 1.0.0'
end

target 'DDCryptorTests' do
    pod 'OpenSSL-Universal', '~> 1.0'
    pod 'GTMBase64', '~> 1.0.0'
end
